package com.verisign.schemas.vip._2011._04.vipuserservices.query;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Jun 13 20:12:32 CDT 2013
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices/query", name = "QueryServicePort")
@XmlSeeAlso({com.verisign.schemas.vip._2011._04.vipuserservices.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryServicePort {

    @WebResult(name = "GetUserInfoResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "GetUserInfoResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.GetUserInfoResponseType getUserInfo(
        @WebParam(partName = "GetUserInfoRequest", name = "GetUserInfoRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.GetUserInfoRequestType getUserInfoRequest
    );

    @WebResult(name = "GetCredentialInfoResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "GetCredentialInfoResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.GetCredentialInfoResponseType getCredentialInfo(
        @WebParam(partName = "GetCredentialInfoRequest", name = "GetCredentialInfoRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.GetCredentialInfoRequestType getCredentialInfoRequest
    );

    @WebResult(name = "GetTemporaryPasswordAttributesResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "GetTemporaryPasswordAttributesResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.GetTemporaryPasswordAttributesResponseType getTemporaryPasswordAttributes(
        @WebParam(partName = "GetTemporaryPasswordAttributesRequest", name = "GetTemporaryPasswordAttributesRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.GetTemporaryPasswordAttributesRequestType getTemporaryPasswordAttributesRequest
    );

    @WebResult(name = "GetServerTimeResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "GetServerTimeResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.GetServerTimeResponseType getServerTime(
        @WebParam(partName = "GetServerTimeRequest", name = "GetServerTimeRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.GetServerTimeRequestType getServerTimeRequest
    );
}
