package com.verisign.schemas.vip._2011._04.vipuserservices.mgmt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Jun 13 20:13:21 CDT 2013
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices/mgmt", name = "ManagementServicePort")
@XmlSeeAlso({com.verisign.schemas.vip._2011._04.vipuserservices.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ManagementServicePort {

    @WebResult(name = "SendOtpResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "SendOtpResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.SendOtpResponseType sendOtp(
        @WebParam(partName = "SendOtpRequest", name = "SendOtpRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.SendOtpRequestType sendOtpRequest
    );

    @WebResult(name = "SetTemporaryPasswordAttributesResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "SetTemporaryPasswordAttributesResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.SetTemporaryPasswordAttributesResponseType setTemporaryPasswordAttributes(
        @WebParam(partName = "SetTemporaryPasswordAttributesRequest", name = "SetTemporaryPasswordAttributesRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.SetTemporaryPasswordAttributesRequestType setTemporaryPasswordAttributesRequest
    );

    @WebResult(name = "RegisterResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "RegisterResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.RegisterResponseType register(
        @WebParam(partName = "RegisterRequest", name = "RegisterRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.RegisterRequestType registerRequest
    );

    @WebResult(name = "RemoveCredentialResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "RemoveCredentialResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.RemoveCredentialResponseType removeCredential(
        @WebParam(partName = "RemoveCredentialRequest", name = "RemoveCredentialRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.RemoveCredentialRequestType removeCredentialRequest
    );

    @WebResult(name = "ClearUserPinResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "ClearUserPinResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.ClearUserPinResponseType clearUserPin(
        @WebParam(partName = "ClearUserPinRequest", name = "ClearUserPinRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.ClearUserPinRequestType clearUserPinRequest
    );

    @WebResult(name = "UpdateCredentialResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "UpdateCredentialResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.UpdateCredentialResponseType updateCredential(
        @WebParam(partName = "UpdateCredentialRequest", name = "UpdateCredentialRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.UpdateCredentialRequestType updateCredentialRequest
    );

    @WebResult(name = "DeleteUserResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "DeleteUserResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.DeleteUserResponseType deleteUser(
        @WebParam(partName = "DeleteUserRequest", name = "DeleteUserRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.DeleteUserRequestType deleteUserRequest
    );

    @WebResult(name = "AddCredentialResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "AddCredentialResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.AddCredentialResponseType addCredential(
        @WebParam(partName = "AddCredentialRequest", name = "AddCredentialRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.AddCredentialRequestType addCredentialRequest
    );

    @WebResult(name = "SetTemporaryPasswordResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "SetTemporaryPasswordResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.SetTemporaryPasswordResponseType setTemporaryPassword(
        @WebParam(partName = "SetTemporaryPasswordRequest", name = "SetTemporaryPasswordRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.SetTemporaryPasswordRequestType setTemporaryPasswordRequest
    );

    @WebResult(name = "CreateUserResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "CreateUserResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.CreateUserResponseType createUser(
        @WebParam(partName = "CreateUserRequest", name = "CreateUserRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.CreateUserRequestType createUserRequest
    );

    @WebResult(name = "ClearTemporaryPasswordResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "ClearTemporaryPasswordResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.ClearTemporaryPasswordResponseType clearTemporaryPassword(
        @WebParam(partName = "ClearTemporaryPasswordRequest", name = "ClearTemporaryPasswordRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.ClearTemporaryPasswordRequestType clearTemporaryPasswordRequest
    );

    @WebResult(name = "UpdateUserResponse", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices", partName = "UpdateUserResponse")
    @WebMethod
    public com.verisign.schemas.vip._2011._04.vipuserservices.UpdateUserResponseType updateUser(
        @WebParam(partName = "UpdateUserRequest", name = "UpdateUserRequest", targetNamespace = "http://schemas.verisign.com/vip/2011/04/vipuserservices")
        com.verisign.schemas.vip._2011._04.vipuserservices.UpdateUserRequestType updateUserRequest
    );
}
